### ISSUE TITLE
JFXCentral

### ISSUE THREAD

**Issue by dlemmermann** [fair-acc/chart-fx#460]
Would be great if this lib could be added to JFXCentral. Simply add to its data repository.

**Comment by dlemmermann** [comment]
Just realised today that your entry on jfxcentral is still missing. Please add it, charts are always on the wishlist of our visitors. You can also send me a write up (markdown) and a couple of screenshots and I will add it myself.

**Comment by RalphSteinhagen** [comment]
@dlemmermann thanks for the reminder, will do.

As a prolific open-source developer yourself, do you have any recommendations regarding getting users to share what they use your libs for? It is always nice as a motivation to see what is being used for and to tell bosses that not everything is in vain. :smile:

**Comment by dlemmermann** [comment]
The only screenshots I ever got were based on my commercial products or consulting work that I did where we used my libs. This way I had a direct connection to the other developers. I have never seen any screenshots of any apps using any of the controls in GemsFX for example. So I would not be too hopeful that it will be any different for you. Just know that people do use your stuff and that the forks and the stars are the best feedback that is currently available to you.

One thing you could of course try is to contact everybody who submits an issue. You could pull a "screenshot for bug fix" thing on them :-)

**Comment by RalphSteinhagen** [comment]
Done and followed-up [here](https://github.com/dlsc-software-consulting-gmbh/jfxcentral-data/pull/359). Will close this here.
