### ISSUE TITLE
Zoom plugin does not appear to correctly scale the y-axis for contour datasets

### ISSUE THREAD

**Issue by ajackson2681** [fair-acc/chart-fx#508]
**Describe the bug**
I noticed while I was implementing my own project, that when I add the zoomer plugin to an XYPlot, that zooming in does not correctly scale the data for a contour dataset. This is easily reproducible by just running the Histogram2DimSample included in this repository. As you can see in the gif attached, when the chart zooms in, the dataset in the y direction appears to compress, even though the range on they y-axis is getting smaller. The x-axis does not appear to have this problem.

**Environment:**
 - OS: Pop!_OS 21.10
 - Java version: 11.0.14
 - JavaFx version: 13
 - ChartFx version: 11.2.6
 
![hist2d](https://user-images.githubusercontent.com/48104097/163447755-2a150353-8707-4954-bfdc-6c37bf6ea16c.gif)

**Comment by wirew0rm** [comment]
fixed in #534
