### ISSUE TITLE
chart-fx logo

### ISSUE THREAD

**Issue by wirew0rm** [fair-acc/chart-fx#528]
We need a logo for the library.

First sketch:
![icon_sketch](https://user-images.githubusercontent.com/1202371/176210448-31d37a8a-b6fe-48d7-bf46-8a735363e0bd.png)

**Comment by milo-gsi** [comment]
Another idea I'd like to add.

![chart_fx_tm_v1](https://user-images.githubusercontent.com/64780007/176637465-b6dbb5ce-8196-4f1d-9cc0-2239fa83a26a.png)

Color is #fcb342 [FAIR orange]

Font: Rocky (Text) from the Rocky Linux project [SIL Open Font License v1.1]
https://github.com/rocky-linux/rocky-fonts

**Comment by milo-gsi** [comment]
A bit indeed. But I really had to look it up.
