### ISSUE TITLE
Unit tests must be platform independent

### ISSUE THREAD

**Issue by MarsBlessed** [fair-acc/chart-fx#540]
**Describe the bug**
`de.gsi.chart.plugins.DataPointTooltipTest` fails on Windows due to "\n" line separator used in the verify predicates.

**To Reproduce**
Run tests on Windows or just insert `System.setProperty("line.separator", "\r\n");` as the first line in `de.gsi.chart.plugins.DataPointTooltipTest.start(...)`
 
**Environment:**
 - OS: Windows
 - Java version: temurin-11.0.16
 - JavaFx version: 13
 - ChartFx version: 11.2.7

**Comment by MarsBlessed** [comment]
using `System.lineSeparator()` is one of the possible solutions;
`String.sprintf()` with %n is another option here

**Comment by wirew0rm** [comment]
Thank for taking the time to report this and propose fixes. I'll look into it.
