### ISSUE TITLE
blocked when use strokeDashPattern style

### ISSUE THREAD

**Issue by lanny886** [fair-acc/chart-fx#552]
When I set DoubleDataSet style with strokeDashPattern like "strokeDashPattern=5,5,5,5;" and add dataSet to chart ,the window become no response. 

follow the code:

    import de.gsi.chart.XYChart;
    import de.gsi.chart.axes.spi.DefaultNumericAxis;
    import de.gsi.dataset.spi.DoubleDataSet;
    import javafx.application.Application;
    import javafx.application.Platform;
    import javafx.scene.Scene;
    import javafx.stage.Stage;
    import java.util.Random;
    import java.util.concurrent.Executors;
    import java.util.concurrent.ScheduledExecutorService;
    import java.util.concurrent.TimeUnit;
    
    public class DashSample extends Application {
        private ScheduledExecutorService scheduledExecutorService = Executors.newScheduledThreadPool(1);
    
        @Override
        public void start(Stage primaryStage) throws Exception {
            final XYChart chart = new XYChart(new DefaultNumericAxis(), new DefaultNumericAxis());
            chart.setAnimated(false);
            chart.setLegendVisible(false);
    
            final Scene scene = new Scene(chart, 600, 400);
            primaryStage.setTitle(this.getClass().getSimpleName());
            primaryStage.setScene(scene);
            primaryStage.setOnCloseRequest(evt -> Platform.exit());
            primaryStage.show();
    
            scheduledExecutorService.schedule(() -> {
                Platform.runLater(() -> {
                    Random random = new Random();
                    final DoubleDataSet dataSet = new DoubleDataSet("myData");
                    for (int i = 0; i < 10; i++) {
                        dataSet.add(random.nextDouble(), random.nextDouble());
                    }
                    dataSet.setStyle("strokeDashPattern=5,5,5,5;");
                    chart.getDatasets().add(dataSet);
                });
            }, 3, TimeUnit.SECONDS);
        }
    }

**Environment:**
 - OS: window 7 
 - Java version: jdk1.8.0_311
 - ChartFx version: 8.1.5

**Comment by wirew0rm** [comment]
Hey, thanks for the report.

Dashed lines in javafx are known to be very inefficient which is why we have a custom implementation for straight dashed lines used e.g. in the GridRenderer. But in a chart with only 10 points it should not block the UI.
Have you checked in the Debugger where the application thread is blocked? You could also try to use the simpler ReducingLineRenderer. Generally the Dash pattern is parsed and forwarded to the graphics context so either the error is in our css parsing code or it probably hits a javaFx bug.

Please also note that the jdk8 branch of chartFx is not actively maintained anymore and we won't be able to provide support or bugfixes, as there is no actively supported free jdk8 version available.

**Comment by lanny886** [comment]
I debug with it ,found that when doSnapshot [Scene.java] -> Object tkImage = tk.renderToImage(context); -> addRenderJob(re) [QuantumToolkit.java] ,which called serveral times, previous calls succeed, but exist the one that job not run and latch is await()

**Comment by lanny886** [comment]
> Hey, thanks for the report.
> 
> Dashed lines in javafx are known to be very inefficient which is why we have a custom implementation for straight dashed lines used e.g. in the GridRenderer. But in a chart with only 10 points it should not block the UI. Have you checked in the Debugger where the application thread is blocked? You could also try to use the simpler ReducingLineRenderer. Generally the Dash pattern is parsed and forwarded to the graphics context so either the error is in our css parsing code or it probably hits a javaFx bug.
> 
> Please also note that the jdk8 branch of chartFx is not actively maintained anymore and we won't be able to provide support or bugfixes, as there is no actively supported free jdk8 version available.

I debug with it ,found that when doSnapshot [Scene.java] -> Object tkImage = tk.renderToImage(context); -> addRenderJob(re) [QuantumToolkit.java] ,which called serveral times, previous calls succeed, but exist the one that job not run and latch is await()

**Comment by lanny886** [comment]
> Hey, thanks for the report.
> 
> Dashed lines in javafx are known to be very inefficient which is why we have a custom implementation for straight dashed lines used e.g. in the GridRenderer. But in a chart with only 10 points it should not block the UI. Have you checked in the Debugger where the application thread is blocked? You could also try to use the simpler ReducingLineRenderer. Generally the Dash pattern is parsed and forwarded to the graphics context so either the error is in our css parsing code or it probably hits a javaFx bug.
> 
> Please also note that the jdk8 branch of chartFx is not actively maintained anymore and we won't be able to provide support or bugfixes, as there is no actively supported free jdk8 version available.

I debug with it ,found that when run code: final Image hatch = pane.snapshot(null, null); [DashPatternStyle.java] -> Scene.doSnapshot [Node.java] -> Object tkImage = tk.renderToImage(context); [Scene.java] -> addRenderJob(re) [QuantumToolkit.java] , the job not run and latch is await()

**Comment by wirew0rm** [comment]
I'm closing this due to the 8.x version not being actively maintained any more, I hope you can understand that. Feel free to reopen if you re-encounter the problem in the latest release or share your findings/questions here, I'll try to answer as best as I can but I cannot spend time nor can I test locally.
