### ISSUE TITLE
Parameter Measurement does not work with long named dataset

### ISSUE THREAD

**Issue by flef** [fair-acc/chart-fx#564]
**Describe the bug**
When asking to compute a Measurement (for example LowPass filter) on a dataset with a long name (> 17 characters), the result box will become bigger and bigger taking the full screen hiding the chart. (as long as you move your mouse on it).

**To Reproduce**
The problem can be reproduced by asking UI to produce 
 
``` java
 final XYChart chart = new XYChart(new DefaultNumericAxis(), yAxis);
        chart.getPlugins().addAll(new ParameterMeasurements());
(...)

    final DoubleDataSet dataSetWorking = new DoubleDataSet("data set with max");
    final DoubleDataSet dataSetNotWorking = new DoubleDataSet("data set with long name that will produce error");
```

**Environment:**
 - OS: Debian / Windows 7 / Windows 10
 - Java version: 17
 - JavaFx version: 19
 - ChartFx version: 11.2.7

**Comment by flef** [comment]
In pictures :

![Capture d’écran du 2023-01-05 20-42-03](https://user-images.githubusercontent.com/3083331/210866989-827dc66a-8ab8-443e-b378-806f94bb75f9.png)

Then just by mouving the mouse over

![Capture d’écran du 2023-01-05 20-46-39](https://user-images.githubusercontent.com/3083331/210867107-923e4c32-ae80-4a0d-9742-f9ef6e2d4cd9.png)

**Comment by wirew0rm** [comment]
Hey thank you for the report.
I didn't have time to reproduce and the debug the issue but I would suspect that the issue is with this function automatically scaling the textboxes: https://github.com/fair-acc/chart-fx/blob/main/chartfx-chart/src/main/java/io/fair_acc/chartfx/plugins/measurements/utils/CheckedValueField.java#L125
Maybe we should add a check there, which only increases the font size if this doesn't increase the size of the panel.
Please feel free to ask further questions and share your findings/questions/fixes/PRs :) I'll try to look into it, but I cannot make any promises.

**Comment by flef** [comment]
Hey,

That's it ! If you remove this line everything works fine after. Just testing via Reflection. 
I think there is no need to change the font size.

Really sorry for the dirty piece of code :

```java
var pm = new ParameterMeasurements(Side.RIGHT, true);
pm.getChartMeasurements().addListener((ListChangeListener<? super AbstractChartMeasurement>) change -> {
	while (change.next()) {
		if (change.wasAdded()) {
			change.getAddedSubList().forEach(a -> {
				try {
					Field widthPropertyField = a.getValueField().getClass()
							.getDeclaredField("widthChangeListener");
					System.err.println(widthPropertyField);
					widthPropertyField.setAccessible(true);

                                        // Here remove the suspected listener
					a.getValueField().widthProperty().removeListener(
							(ChangeListener<? super Number>) widthPropertyField.get(a.getValueField()));
				} catch (Exception e) {
					System.err.println(e);
				}
			});
		}
	}
});

final XYChart chart = new XYChart(new DefaultNumericAxis(), yAxis);
chart.getPlugins().addAll(new Zoomer(), new CrosshairIndicator(), pm, new EditAxis());
```

Final result : 
![Capture d’écran du 2023-01-10 22-17-17](https://user-images.githubusercontent.com/3083331/211664422-4d35d1b0-77bc-43d2-9cd3-393c8b64ed37.png)

**Comment by wirew0rm** [comment]
I've disabled the font size adjustment for now, can be revisited later if it can be reenabled with some guardrails against growing to infinity.
