### ISSUE TITLE
axisSynchronizer not syncing data properly

### ISSUE THREAD

**Issue by Tharrington86** [fair-acc/chart-fx#565]
Hello,
I am working on a Java application that uses chartFX to graph incoming CAN data that is collected via a serial connection or through a recorded log file. When multiple graphs are added to the window, they fail to stay synchronized when using using a drag and drop zoomer. The axisSynchronizer() is used when a graph is added to the window as follows:
axisSynchronizer.add(telemetryData.getLineChart().getXAxis());

The timestamps (x-axis) are synchronized correctly but the data is not as you can see by the density of the data points.

Any ideas where to look?

**Environment:**
 - OS: Windows 11
 - Java version: 17
 - JavaFx version: 17
 - ChartFx version: [master, 11.2.7] 
![dataNotSyncd](https://user-images.githubusercontent.com/75510358/211059019-7c88cb7a-26c5-4357-b0c3-57bb84fae96b.png)

**Comment by wirew0rm** [comment]
Hey, thanks for reporting this.
I assume your data is not updated periodically, which is something that at the moment still leads to inconsistencies between the axes and data for some cases. I'm working on changing the way the axes are layed out at the moment to make this more consistent, but that's still in the works.

To collect further info about possible workarounds, you can try some of these:
- does it work for panning (actually i suspect there to still be an error of one frame, but it's less noticeable for continous movements)
- does the scaling get fixed if you resize the window (triggering a repaint of the chart)
- does the scaling get fixed if you call `chart.requestLayout()` (maybe add a button to trigger it manually)

Possible workarounds could then be to have a delayed/`runLater` invocation of `chart.requestLayout` for every zoom action.

**Comment by Tharrington86** [comment]
@wirew0rm Thank you for the reply.

The graph has two modes that are toggled by a button. The first mode graphs "live" data as it is received (@every 50ms) and when the "graph buffer" contains 60 seconds worth of data it removes the older data as it writes the newer data . The second mode is a snapshot of the previous 10 minutes of data. 

- Panning/scrolling keeps the data in sync (close enough that the human eye can't detect it, even if it is off a frame)
- Resizing the window does appear to fix the scaling. I will have to dig into the raw data to confirm. 
- I will add a button to call chart.requestLayout() and report back.

**Comment by Tharrington86** [comment]
I was able get behavior that is pretty close to what is intended by using:
`Platform.runLater(() -> graphsStackPane.addEventFilter(MouseEvent.ANY,
                (mouseEvent -> {

                for (TelemetryData graph : activeGraphsList) {
                        graph.getLineChart().requestLayout();
                }
        })));`

I initially tried using MouseEvent.MOUSE_DRAGGED but switched to ANY because the event seems to be a frame behind and triggers on the second action. Now  after the zoom happens, the other graphs are synced on the next mouse event of any kind.
