### ISSUE TITLE
Application does not exit with chartfx

### ISSUE THREAD

**Issue by PavelSpiridonov** [fair-acc/chart-fx#571]
### Discussed in https://github.com/fair-acc/chart-fx/discussions/467

<div type='discussions-op-text'>

<sup>Originally posted by **DennisOlbrich** September 28, 2021</sup>
If any gsi XYchart is used in the FX application, the application will not close, when the last window is closed. Do you have any idea what is wrong?

`package application;

import de.gsi.chart.XYChart;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class XYChartMain extends Application {

	@Override
	public void start(Stage primaryStage) throws Exception {
		XYChart chart = new XYChart();

		AnchorPane ap = new AnchorPane();
		ap.getChildren().add(chart);

		Scene scene = new Scene(ap, 640, 480);
		primaryStage.setScene(scene);

		primaryStage.show();
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		launch(args);
	}
}`</div>

**Comment by milo-gsi** [comment]
Try adding 

```
primaryStage.setOnCloseRequest((e) -> {
	System.exit(0);
});
```

**Comment by ennerf** [comment]
@wirew0rm It looks like this issue was fixed somewhere with the layout changes. The provided sample code now closes properly on `main`.

**Comment by wirew0rm** [comment]
Going though the samples to narrow the problem down, these are still affected:
- ChartIndicatorSample
- DataViewerSample
- ErrorDataSetRendererSample
- Histogram2DimSample
- OscilloscopeAxisSample
- PaddedGrowAxis
- RollingBuffer[SortedTree]Sample
- WaterfallPerformanceSample

So that narrows it down

**Comment by wirew0rm** [comment]
closed as the original Problem seems to be solved. The samples will be fixed by a followup PR
