### ISSUE TITLE
If the dataset is round-trip, when i zoom the chart, the line will disapear.

### ISSUE THREAD

**Issue by JungleHH** [fair-acc/chart-fx#584]
**Describe the bug**
My program goal is do some loop test. So the data will be round-trip. When zoom the chart, the line will disapear. 
I can reproduce this problem on a sample program（ChartPerformanceGraph）.

**To Reproduce**
Here is the Reproduce：
![Uploading 61hiu-n1xkw.gif…]()

Here is the data sample:
[sampleData.txt](https://github.com/fair-acc/chart-fx/files/11352405/sampleData.txt)

``` 
    public void initChartPane(Pane parent) {
        PlatformData.historyDataset = new FifoDoubleErrorDataSet("position", GlobalManager.realtimeLimit);
        DefaultNumericAxis xAxis = new DefaultNumericAxis("position", "mm");
        xAxis.setAutoRangeRounding(true);
        xAxis.setAutoRangePadding(0.2);
        DefaultNumericAxis yAxis = new DefaultNumericAxis("force", "mN");
        yAxis.setAutoRangeRounding(true);
        yAxis.setAutoRangePadding(0.2);
        Chart chart = new XYChart(xAxis, yAxis);
        chart.setAnimated(false);
        chart.setPrefWidth(1000);
        chart.setPrefHeight(600);
        chart.setLegendVisible(false);
        chart.getPlugins().add(new Zoomer());
        chart.getPlugins().add(new DataPointTooltip());
        chart.getDatasets().add(PlatformData.historyDataset);
        parent.getChildren().add(chart);

        final XValueIndicator xValueIndicator = new XValueIndicator(xAxis, 20, "mark");
        chart.getPlugins().add(xValueIndicator);
    }
```

**Environment:**
 - OS: [Windows 10]
 - Java version: OpenJDK 17
 - JavaFx version:  OpenJFX 13
 - ChartFx version: [11.2.7 - master]

**Comment by JungleHH** [comment]
Sorry, The gif upload failed , Here it is:
![61hiu-n1xkw](https://user-images.githubusercontent.com/24989159/235124804-78baf84b-db88-4c34-93b4-df51a5bb2951.gif)

**Comment by wirew0rm** [comment]
Should be solved by `renderer.setAssumeSortedData(false)`. If it isn't also try do disable data reduction.

For performance considerations the algorithms assume that the x coordinate of the dataset is sorted, setting the property disables certain optimisations. For the size of your dataset the perfomance impact shouldn't be a problem though.

**Comment by JungleHH** [comment]
Thanks for your reply, it works well! Eventually, the max size of my dataset could be 20,000 .

**Comment by wirew0rm** [comment]
Good! I'll close this issue as solved.

20k points should still work reasonably well and if it doesn't you can always reduce your dataset before or implement a custom renderer/datareducer based on the existing ones.
