### ISSUE TITLE
DragResizerUtil dont resize on south

### ISSUE THREAD

**Issue by rsuna** [fair-acc/chart-fx#605]
**Describe the bug**
Its not possible to resize a region by south, is a small copy&paste mistake. PR is pending.

**To Reproduce**
Try to resize a component at the bottom is not working.

**Environment:**
 - OS: WIndows10
 - Java version: 11
 - JavaFx version:  11
 - ChartFx version: 11.2.2

**Comment by RalphSteinhagen** [comment]
closing as fixed by already merged PR #606
