### ISSUE TITLE
Axis display problem

### ISSUE THREAD

**Issue by zkycaesar** [fair-acc/chart-fx#610]
I am drawing a XYChart, and creating axis like this: `DefaultNumericAxis xAxis = new DefaultNumericAxis(null, null);`
The param `axisLabel` and `unit` are both set to null, in order to hide the name label (not sure that is the correct way). 
The chart shows like this:
![image](https://github.com/fair-acc/chart-fx/assets/17026668/184a43ea-36d0-479a-a7e1-5eac39a7c0b6)
The axis is not showing fully. I use a BorderPane to contain the chart, when I resize the pane, the chart will also resize, but the axis keeps showing like that. 
What seems to be the problem?

**Comment by ennerf** [comment]
This is related to a layout bug that will be fixed by the next release

**Comment by wirew0rm** [comment]
I'll close this since 11.3.0 is now released and presumably fixes this issue. Feel free to reopen if the the issue persists with the current release.
