### ISSUE TITLE
Several questions about axis

### ISSUE THREAD

**Issue by zkycaesar** [fair-acc/chart-fx#632]
I am using the version 11.3.0, and encountered some problems:
### Question 1
![image](https://github.com/fair-acc/chart-fx/assets/17026668/fc99f06b-2d01-4517-a530-518b4b69d258)
"0" is half hidden. Is that a bug?
### Question 2
![image](https://github.com/fair-acc/chart-fx/assets/17026668/87e0a0d4-03f1-4b13-a953-fda8650dc206)
I want the max value and the min value to be shown on the axis. Is there a way to do that?
### Question 3
![image](https://github.com/fair-acc/chart-fx/assets/17026668/41c85bf9-6728-437b-9172-7b25ef4476cc)
When I set autoRangePadding to 0.1, it seems not both side take effect. Why is that?

**Comment by ennerf** [comment]
Thanks for reporting. 

### Q1

Can you provide a minimum reproducible sample? Are you maybe using an axis padding of `0` or adding something to the bottom-left corner?

### Q2

You can use X and Y indicators

### Q3

That part of the code shouldn't have changed compared to 11.2.7. Can you add this to the sample?

**Comment by zkycaesar** [comment]
> ### Q1
> Can you provide a minimum reproducible sample? Are you by any chance disabling [axis padding](https://github.com/fair-acc/chart-fx/blob/ed86318c5a1bde23d285633a94860648aee5fb32/chartfx-chart/src/main/resources/io/fair_acc/chartfx/chart.scss#L296) or adding something to the bottom-left corner?

@ennerf Yes you are right. I set `-fx-axis-padding: 1` in css file. I don't remember why I did that. My bad, sorry.
