### ISSUE TITLE
(1) real time candlestick Chart with lines and points together (2) show at least two candlesticks together

### ISSUE THREAD

**Issue by yezhengli-Mr9** [fair-acc/chart-fx#643]
### Discussed in https://github.com/fair-acc/chart-fx/discussions/641

<div type='discussions-op-text'>

<sup>Originally posted by **yezhengli-Mr9** November 20, 2023</sup>
Can provide sample source code if necessary in the near future.
(1) Try to draw real-time candlestick Chart with lines and points together.  By lines and points, I mean for example, combination of vertical and horizontal lines to show support point and alert trigger point. 
(1a) no need to show arrow; lines are good.
(2a) even rectangles instead of combination of horizontal and vertical lines are OK.
(2) better show at least two candlesticks together -- so far any way is fine: for example, 
(2a) side by side 
(2b) put two candlesticks on one chart.
<img width="1734" alt="DailyMarketStream 2023-11-20 07-32-27" src="https://github.com/fair-acc/chart-fx/assets/16505983/b1fd7c24-f8ee-49e9-8120-a33ac5e85554">

Try to use `addPaintAfterEp(...)` in following potentially helpful examples while following samples provide blank or non-instructive output charts?
https://github.com/fair-acc/chart-fx/blob/ed86318c5a1bde23d285633a94860648aee5fb32/chartfx-samples/src/main/java/io/fair_acc/sample/financial/FinancialPositionSample.java#L45
https://github.com/fair-acc/chart-fx/blob/ed86318c5a1bde23d285633a94860648aee5fb32/chartfx-samples/src/main/java/io/fair_acc/sample/financial/FinancialRealtimeFootprintSample.java#L58
![image](https://github.com/fair-acc/chart-fx/assets/16505983/465d254f-1966-4858-9da7-15d6a011e96b)
![image](https://github.com/fair-acc/chart-fx/assets/16505983/68672159-2e67-4f54-8bef-f91e3142f9d0)

On the other hand, `addPaintAfterEp(...)` in following can provide `Color.MAGENTA` as designed  https://github.com/fair-acc/chart-fx/blob/ed86318c5a1bde23d285633a94860648aee5fb32/chartfx-samples/src/main/java/io/fair_acc/sample/financial/FinancialRealtimeCandlestickSample.java#L117
![image](https://github.com/fair-acc/chart-fx/assets/16505983/e757c16e-feb7-4327-972d-9d3b2be57a76)
</div>

**Comment by wirew0rm** [comment]
No need to duplicate this into the issues
