### ISSUE TITLE
Inquiry about Documentation

### ISSUE THREAD

**Issue by 8tothepowerof9** [fair-acc/chart-fx#651]
I'm relatively new to Java and currently exploring your repository. I was wondering if there is any documentation available to help beginners get started with understanding the classes and functionality provided by the project. Thanks in advance for your assistance!

**Comment by ennerf** [comment]
IMO the easiest way to learn about it would be to download the [pre-packaged sampler](https://files.hebi.us/internal/demo/chartfx-sampler/download.html) and check the corresponding [code samples](https://github.com/fair-acc/chart-fx/tree/main/chartfx-samples/src/main/java/io/fair_acc/sample/chart).

**Comment by 8tothepowerof9** [comment]
thanks !!
