### ISSUE TITLE
Broken handling of Y error values by multi-value LimitedIndexedTreeDataSet.set

### ISSUE THREAD

**Issue by zanzica** [fair-acc/chart-fx#652]
**Describe the bug**
There is a coding error (probably copy-paste) in `LimitedIndexedTreeDataSet .set` that causes the y error values to be ignored, with the y values erroneously used in their place.

[Permalink](https://github.com/fair-acc/chart-fx/blob/ed86318c5a1bde23d285633a94860648aee5fb32/chartfx-dataset/src/main/java/io/fair_acc/dataset/spi/LimitedIndexedTreeDataSet.java#L447C17-L450C46)

Snippet:
```java
public LimitedIndexedTreeDataSet set(final double[] xValues, final double[] yValues, final double[] xErrors,
            final double[] yErrors, final int count) {
...
                final double x = xValues[i];
                final double y = yValues[i];
                final double dx = xErrors[i];
                final double dy = yValues[i]; // this should be yErrors[i]
...
```

**Comment by wirew0rm** [comment]
Thanks for letting us know :+1:
