### ISSUE TITLE
ErrorDataSetRenderer.setDrawBars(false) has no effect

### ISSUE THREAD

**Issue by wolfig** [fair-acc/chart-fx#685]
**Affects version 11.3.1

**Error Description
I initialize an XYChart as follows:

    public DeviceAutomatorXYChart() {
        _renderer = new ErrorDataSetRenderer();
        _renderer.setId("MainRenderer");
        _renderer.setErrorStyle(ErrorStyle.ERRORBARS);
        _renderer.setDrawMarker(true);
        _renderer.setShowInLegend(false);
        _renderer.getAxes().setAll(_xyChart.getAxes());
        _renderer.setDrawBars(false);  <-----!!!!
        _xyChart.setLegendVisible(false);
        _xyChart.getRenderers().clear();
        _xyChart.getRenderers().add(_renderer);
    }
I'd expect that error bars are not rendered even if the error values in the data set are larger than 0.0. However, this is not the case, error bars are displayed nevertheless.

**Comment by wirew0rm** [comment]
This seems to be just a wrong assumption on what the function does. You can set it to true to observe that it actually has a (different) effect ;)

`_renderer.setErrorStyle(ErrorStyle.ERRORBARS);` -> draw errors as bars

`_renderer.setDrawBars(false);` -> do not draw the data points as histogram style bars from y=0 (this is the default anyway) and the [documentation](https://github.com/fair-acc/chart-fx/blob/main/chartfx-chart/src/main/java/io/fair_acc/chartfx/renderer/spi/AbstractErrorDataSetRendererParameter.java#L322-L323) on this is also pretty clear I think.

I'll close this as I'm pretty sure this should clarify this, feel free to comment/reopen if this doesn't solve the problem of if you have ideas on how to make this more obvious. Have a nice weekend!
